name: Flutter CI/CD - Build and Release

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Run unit tests
        run: flutter test

      - name: Check if Android Keystore is available
        id: android-keystore
        run: |
          if [[ -z "${{ secrets.ANDROID_KEYSTORE }}" ]]; then
            echo "ANDROID_KEYSTORE is missing, proceeding with unsigned APK build"
            echo "signing=false" >> $GITHUB_ENV
          else
            echo "ANDROID_KEYSTORE is present, proceeding with signed APK build"
            echo "signing=true" >> $GITHUB_ENV
          fi

      - name: Decode Android Keystore (base64) if present
        if: env.signing == 'true'
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > android/app/release-keystore.jks

      - name: Configure Android signing if present
        if: env.signing == 'true'
        run: |
          cat >> android/key.properties <<EOF
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          storeFile=release-keystore.jks
          EOF

      - name: Build Android APK
        run: flutter build apk --release

      - name: Build Android App Bundle (AAB)
        run: flutter build appbundle --release

      - name: Build iOS IPA (unsigned)
        run: flutter build ipa --no-codesign

      - name: Generate new version tag
        id: tagger
        run: |
          git fetch --tags
          LATEST_TAG=$(git tag --sort=-v:refname | head -n 1)
          echo "Latest tag: $LATEST_TAG"

          if [[ "$LATEST_TAG" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
            MAJOR=${BASH_REMATCH[1]}
            MINOR=${BASH_REMATCH[2]}
            PATCH=${BASH_REMATCH[3]}
            PATCH=$((PATCH + 1))
          else
            MAJOR=1
            MINOR=0
            PATCH=0
          fi

          NEW_TAG="v$MAJOR.$MINOR.$PATCH"
          echo "New tag: $NEW_TAG"
          echo "tag_name=$NEW_TAG" >> $GITHUB_OUTPUT

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag $NEW_TAG
          git push https://x-access-token:${{ secrets.MYTOKEN }}@github.com/${{ github.repository }} --tags

      - name: Upload APK to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tagger.outputs.tag_name }}
          name: Release ${{ steps.tagger.outputs.tag_name }}
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.MYTOKEN }}

      - name: Upload AAB to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tagger.outputs.tag_name }}
          name: Release ${{ steps.tagger.outputs.tag_name }}
          files: build/app/outputs/bundle/release/app-release.aab
        env:
          GITHUB_TOKEN: ${{ secrets.MYTOKEN }}

      - name: Upload IPA to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tagger.outputs.tag_name }}
          name: Release ${{ steps.tagger.outputs.tag_name }}
          files: build/ios/ipa/*.ipa
        env:
          GITHUB_TOKEN: ${{ secrets.MYTOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tagger.outputs.tag_name }}
          name: Release ${{ steps.tagger.outputs.tag_name }}
          body: "Automated release for version ${{ steps.tagger.outputs.tag_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.MYTOKEN }}
